name: tests

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v44
              with:
                  files: |
                      packages/**/*.{nr,toml}

            - if: steps.changed-files.outputs.any_changed == 'true'
              name: Install Nargo
              uses: noir-lang/noirup@v0.1.3
              with:
                  toolchain: 0.26.0

            - if: steps.changed-files.outputs.any_changed == 'true'
              name: Test circuits
              run: yarn test
